#!/usr/bin/env node
// aldus/worker/build-engine.mjs — bundle the match engine of the original project for the Worker.
//
//   node build-engine.mjs      → engine/data-text.generated.js, engine/engine.bundle.js
//
// engine/glue.js imports server/match, server/sim and shared/ as they are. Three things keep them from running in a
// Worker as files, and each one is solved here, in the bundle, never in the sources:
//
//   * They are many files. A Worker is one module graph that wrangler uploads: esbuild makes one file of them.
//   * server/data.js reads data/*.json from a disk, and a Worker has none. The data goes into the bundle as text
//     (data-text.generated.js) and engine/stubs/fs.js answers the two calls server/data.js makes. It stays text until
//     the first match needs it: a Worker has a short time limit to start, and 3.4 MB of JSON is not parsed in it.
//   * The simulation takes its Node path when `process` exists (server/sim/simdata.js IS_NODE). `process` is defined
//     as absent in the bundle, so the simulation takes its browser path and the glue gives it the data, as a page does.
////   * server/sim/content/index.js loads the kits and the content modules with `import(path)`, a path it builds at run
//     time: a browser fetches them, a bundler cannot see them. The plugin below gives that one file a table of every
//     module of its folder, each behind a literal `import()`, and sends its `import(path)` to the table. If the line
//     is not there any more, the build stops: the loader changed and this file has to follow.
//
// data/assets.json is left out: it lists the art of the browser client, and no server code reads it.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { build } from 'esbuild';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, '..', '..');
const DATA_SKIP = new Set(['assets.json', 'local-assets.json']);

const CONTENT_DIR = path.join(ROOT, 'server', 'sim', 'content');
const DYNAMIC_IMPORT = 'return await import(path);';

/** Every `.js` file under `dir`, as `./a/b.js`, sorted. */
function modulesUnder(dir, rel = '.') {
  const out = [];
  for (const d of fs.readdirSync(path.join(dir, rel), { withFileTypes: true })) {
    if (d.isDirectory()) out.push(...modulesUnder(dir, `${rel}/${d.name}`));
    else if (d.isFile() && d.name.endsWith('.js')) out.push(`${rel}/${d.name}`);
  }
  return out.sort();
}

/**
 * A content loader with its run-time imports made visible to the bundler (see the header): `source` is a file of
 * server/sim/content that has DYNAMIC_IMPORT; `file` is its path. Returns null for a file without that line.
 */
export function staticContentLoader(source, file) {
  const parts = source.split(DYNAMIC_IMPORT).length - 1;
  if (parts === 0) return null;
  if (parts !== 1) throw new Error(`${path.relative(ROOT, file)}: ${parts} run-time imports — its loader changed, update aldus/worker/build-engine.mjs`);
  const self = `./${path.basename(file)}`;
  const mods = modulesUnder(path.dirname(file)).filter((m) => m !== self);
  const table = `const __spContent = {\n${mods.map((m) => `  ${JSON.stringify(m)}: () => import(${JSON.stringify(m)}),`).join('\n')}\n};\n`;
  const call = 'if (!Object.hasOwn(__spContent, path)) throw new Error(`no content module ${path} in the bundle`); return await __spContent[path]();';
  return { code: table + source.replace(DYNAMIC_IMPORT, call), modules: mods };
}

/** The files of server/sim/content that load modules at run time. */
export const contentLoaders = () => modulesUnder(CONTENT_DIR)
  .map((m) => path.join(CONTENT_DIR, m))
  .filter((f) => fs.readFileSync(f, 'utf8').includes(DYNAMIC_IMPORT));

const contentPlugin = {
  name: 'sp-static-content',
  setup(b) {
    b.onLoad({ filter: /[\\/]server[\\/]sim[\\/]content[\\/].*\.js$/ }, (args) => {
      const made = staticContentLoader(fs.readFileSync(args.path, 'utf8'), args.path);
      return made ? { contents: made.code, loader: 'js', resolveDir: path.dirname(args.path) } : null;
    });
  },
};

export async function buildEngine({ out = path.join(HERE, 'engine', 'engine.bundle.js'), log = () => {} } = {}) {
  const dataDir = path.join(ROOT, 'data');
  const files = fs.readdirSync(dataDir).filter((f) => f.endsWith('.json') && !DATA_SKIP.has(f)).sort();
  if (!files.includes('chess.json')) throw new Error(`no game data in ${dataDir}`);
  const entries = files.map((f) => {
    const text = fs.readFileSync(path.join(dataDir, f), 'utf8');
    JSON.parse(text); // a broken file stops the build, not the first match
    return `  ${JSON.stringify(f)}: ${JSON.stringify(text)},`;
  });
  fs.writeFileSync(path.join(HERE, 'engine', 'data-text.generated.js'),
    `// Generated by build-engine.mjs from data/*.json. Do not edit.\nexport const DATA_TEXT = {\n${entries.join('\n')}\n};\n`);

  const stub = (name) => path.join(HERE, 'engine', 'stubs', `${name}.js`);
  const res = await build({
    entryPoints: [path.join(HERE, 'engine', 'glue.js')],
    outfile: out,
    bundle: true,
    format: 'esm',
    platform: 'neutral',
    target: 'es2022',
    minifySyntax: true,
    minifyWhitespace: true,
    legalComments: 'none',
    alias: { 'node:fs': stub('fs'), 'node:path': stub('path'), 'node:url': stub('url'), 'node:crypto': stub('crypto'), 'node:net': stub('net') },
    define: { process: 'undefined' },
    plugins: [contentPlugin],
    metafile: true,
    logLevel: 'warning',
  });
  const inputs = Object.keys(res.metafile.inputs);
  // the HTTP server of the original project and any npm package have no place in the Worker
  const bad = inputs.filter((f) => /(^|\/)node_modules\//.test(f) || /(^|\/)server\/index\.js$/.test(f));
  if (bad.length) throw new Error(`the engine bundle pulled in files it must not: ${bad.join(', ')}`);
  // a run-time import that is left would fail in the Worker on the first match, not here
  if (!contentLoaders().length) throw new Error('server/sim/content has no run-time loader any more: remove the plugin from aldus/worker/build-engine.mjs');
  const left = fs.readFileSync(out, 'utf8').match(/\bimport\((?!["'`])[^)]*\)/g);
  if (left) throw new Error(`the engine bundle still imports at run time: ${[...new Set(left)].join(', ')}`);
  const bytes = fs.statSync(out).size;
  log(`engine: ${inputs.length} modules, ${files.length} data files → ${path.relative(ROOT, out)} (${(bytes / 1048576).toFixed(1)} MB)`);
  return { out, bytes, modules: inputs.length, dataFiles: files };
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  buildEngine({ log: (l) => console.log(l) }).catch((e) => { console.error(`✖ ${e.message}`); process.exit(1); });
}
